#!/bin/bash

# Crear la tabla catalogo_de_productos con una familia de columnas llamada 'info'
echo "Creando la tabla 'catalogo_de_productos' en HBase..."
hbase shell <<EOF
create 'catalogo_de_productos', 'info'
EOF

# Insertar productos en la tabla
echo "Insertando productos en la tabla 'catalogo_de_productos'..."

hbase shell <<EOF
put 'catalogo_de_productos', '1', 'info:nombre', 'Producto 1'
put 'catalogo_de_productos', '1', 'info:descripcion', 'Descripción del producto 1'
put 'catalogo_de_productos', '1', 'info:precio', '10'
put 'catalogo_de_productos', '1', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '1', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '2', 'info:nombre', 'Producto 2'
put 'catalogo_de_productos', '2', 'info:descripcion', 'Descripción del producto 2'
put 'catalogo_de_productos', '2', 'info:precio', '20'
put 'catalogo_de_productos', '2', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '2', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '3', 'info:nombre', 'Producto 3'
put 'catalogo_de_productos', '3', 'info:descripcion', 'Descripción del producto 3'
put 'catalogo_de_productos', '3', 'info:precio', '30'
put 'catalogo_de_productos', '3', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '3', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '4', 'info:nombre', 'Producto 4'
put 'catalogo_de_productos', '4', 'info:descripcion', 'Descripción del producto 4'
put 'catalogo_de_productos', '4', 'info:precio', '40'
put 'catalogo_de_productos', '4', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '4', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '5', 'info:nombre', 'Producto 5'
put 'catalogo_de_productos', '5', 'info:descripcion', 'Descripción del producto 5'
put 'catalogo_de_productos', '5', 'info:precio', '50'
put 'catalogo_de_productos', '5', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '5', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '6', 'info:nombre', 'Producto 6'
put 'catalogo_de_productos', '6', 'info:descripcion', 'Descripción del producto 6'
put 'catalogo_de_productos', '6', 'info:precio', '60'
put 'catalogo_de_productos', '6', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '6', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '7', 'info:nombre', 'Producto 7'
put 'catalogo_de_productos', '7', 'info:descripcion', 'Descripción del producto 7'
put 'catalogo_de_productos', '7', 'info:precio', '70'
put 'catalogo_de_productos', '7', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '7', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '8', 'info:nombre', 'Producto 8'
put 'catalogo_de_productos', '8', 'info:descripcion', 'Descripción del producto 8'
put 'catalogo_de_productos', '8', 'info:precio', '80'
put 'catalogo_de_productos', '8', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '8', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '9', 'info:nombre', 'Producto 9'
put 'catalogo_de_productos', '9', 'info:descripcion', 'Descripción del producto 9'
put 'catalogo_de_productos', '9', 'info:precio', '90'
put 'catalogo_de_productos', '9', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '9', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '10', 'info:nombre', 'Producto 10'
put 'catalogo_de_productos', '10', 'info:descripcion', 'Descripción del producto 10'
put 'catalogo_de_productos', '10', 'info:precio', '100'
put 'catalogo_de_productos', '10', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '10', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '11', 'info:nombre', 'Producto 11'
put 'catalogo_de_productos', '11', 'info:descripcion', 'Descripción del producto 11'
put 'catalogo_de_productos', '11', 'info:precio', '110'
put 'catalogo_de_productos', '11', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '11', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '12', 'info:nombre', 'Producto 12'
put 'catalogo_de_productos', '12', 'info:descripcion', 'Descripción del producto 12'
put 'catalogo_de_productos', '12', 'info:precio', '120'
put 'catalogo_de_productos', '12', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '12', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '13', 'info:nombre', 'Producto 13'
put 'catalogo_de_productos', '13', 'info:descripcion', 'Descripción del producto 13'
put 'catalogo_de_productos', '13', 'info:precio', '130'
put 'catalogo_de_productos', '13', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '13', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '14', 'info:nombre', 'Producto 14'
put 'catalogo_de_productos', '14', 'info:descripcion', 'Descripción del producto 14'
put 'catalogo_de_productos', '14', 'info:precio', '140'
put 'catalogo_de_productos', '14', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '14', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '15', 'info:nombre', 'Producto 15'
put 'catalogo_de_productos', '15', 'info:descripcion', 'Descripción del producto 15'
put 'catalogo_de_productos', '15', 'info:precio', '150'
put 'catalogo_de_productos', '15', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '15', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '16', 'info:nombre', 'Producto 16'
put 'catalogo_de_productos', '16', 'info:descripcion', 'Descripción del producto 16'
put 'catalogo_de_productos', '16', 'info:precio', '160'
put 'catalogo_de_productos', '16', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '16', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '17', 'info:nombre', 'Producto 17'
put 'catalogo_de_productos', '17', 'info:descripcion', 'Descripción del producto 17'
put 'catalogo_de_productos', '17', 'info:precio', '170'
put 'catalogo_de_productos', '17', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '17', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '18', 'info:nombre', 'Producto 18'
put 'catalogo_de_productos', '18', 'info:descripcion', 'Descripción del producto 18'
put 'catalogo_de_productos', '18', 'info:precio', '180'
put 'catalogo_de_productos', '18', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '18', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '19', 'info:nombre', 'Producto 19'
put 'catalogo_de_productos', '19', 'info:descripcion', 'Descripción del producto 19'
put 'catalogo_de_productos', '19', 'info:precio', '190'
put 'catalogo_de_productos', '19', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '19', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '20', 'info:nombre', 'Producto 20'
put 'catalogo_de_productos', '20', 'info:descripcion', 'Descripción del producto 20'
put 'catalogo_de_productos', '20', 'info:precio', '200'
put 'catalogo_de_productos', '20', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '20', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '21', 'info:nombre', 'Producto 21'
put 'catalogo_de_productos', '21', 'info:descripcion', 'Descripción del producto 21'
put 'catalogo_de_productos', '21', 'info:precio', '210'
put 'catalogo_de_productos', '21', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '21', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '22', 'info:nombre', 'Producto 22'
put 'catalogo_de_productos', '22', 'info:descripcion', 'Descripción del producto 22'
put 'catalogo_de_productos', '22', 'info:precio', '220'
put 'catalogo_de_productos', '22', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '22', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '23', 'info:nombre', 'Producto 23'
put 'catalogo_de_productos', '23', 'info:descripcion', 'Descripción del producto 23'
put 'catalogo_de_productos', '23', 'info:precio', '230'
put 'catalogo_de_productos', '23', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '23', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '24', 'info:nombre', 'Producto 24'
put 'catalogo_de_productos', '24', 'info:descripcion', 'Descripción del producto 24'
put 'catalogo_de_productos', '24', 'info:precio', '240'
put 'catalogo_de_productos', '24', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '24', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '25', 'info:nombre', 'Producto 25'
put 'catalogo_de_productos', '25', 'info:descripcion', 'Descripción del producto 25'
put 'catalogo_de_productos', '25', 'info:precio', '250'
put 'catalogo_de_productos', '25', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '25', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '26', 'info:nombre', 'Producto 26'
put 'catalogo_de_productos', '26', 'info:descripcion', 'Descripción del producto 26'
put 'catalogo_de_productos', '26', 'info:precio', '260'
put 'catalogo_de_productos', '26', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '26', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '27', 'info:nombre', 'Producto 27'
put 'catalogo_de_productos', '27', 'info:descripcion', 'Descripción del producto 27'
put 'catalogo_de_productos', '27', 'info:precio', '270'
put 'catalogo_de_productos', '27', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '27', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '28', 'info:nombre', 'Producto 28'
put 'catalogo_de_productos', '28', 'info:descripcion', 'Descripción del producto 28'
put 'catalogo_de_productos', '28', 'info:precio', '280'
put 'catalogo_de_productos', '28', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '28', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '29', 'info:nombre', 'Producto 29'
put 'catalogo_de_productos', '29', 'info:descripcion', 'Descripción del producto 29'
put 'catalogo_de_productos', '29', 'info:precio', '290'
put 'catalogo_de_productos', '29', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '29', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '30', 'info:nombre', 'Producto 30'
put 'catalogo_de_productos', '30', 'info:descripcion', 'Descripción del producto 30'
put 'catalogo_de_productos', '30', 'info:precio', '300'
put 'catalogo_de_productos', '30', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '30', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '31', 'info:nombre', 'Producto 31'
put 'catalogo_de_productos', '31', 'info:descripcion', 'Descripción del producto 31'
put 'catalogo_de_productos', '31', 'info:precio', '310'
put 'catalogo_de_productos', '31', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '31', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '32', 'info:nombre', 'Producto 32'
put 'catalogo_de_productos', '32', 'info:descripcion', 'Descripción del producto 32'
put 'catalogo_de_productos', '32', 'info:precio', '320'
put 'catalogo_de_productos', '32', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '32', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '33', 'info:nombre', 'Producto 33'
put 'catalogo_de_productos', '33', 'info:descripcion', 'Descripción del producto 33'
put 'catalogo_de_productos', '33', 'info:precio', '330'
put 'catalogo_de_productos', '33', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '33', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '34', 'info:nombre', 'Producto 34'
put 'catalogo_de_productos', '34', 'info:descripcion', 'Descripción del producto 34'
put 'catalogo_de_productos', '34', 'info:precio', '340'
put 'catalogo_de_productos', '34', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '34', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '35', 'info:nombre', 'Producto 35'
put 'catalogo_de_productos', '35', 'info:descripcion', 'Descripción del producto 35'
put 'catalogo_de_productos', '35', 'info:precio', '350'
put 'catalogo_de_productos', '35', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '35', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '36', 'info:nombre', 'Producto 36'
put 'catalogo_de_productos', '36', 'info:descripcion', 'Descripción del producto 36'
put 'catalogo_de_productos', '36', 'info:precio', '360'
put 'catalogo_de_productos', '36', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '36', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '37', 'info:nombre', 'Producto 37'
put 'catalogo_de_productos', '37', 'info:descripcion', 'Descripción del producto 37'
put 'catalogo_de_productos', '37', 'info:precio', '370'
put 'catalogo_de_productos', '37', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '37', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '38', 'info:nombre', 'Producto 38'
put 'catalogo_de_productos', '38', 'info:descripcion', 'Descripción del producto 38'
put 'catalogo_de_productos', '38', 'info:precio', '380'
put 'catalogo_de_productos', '38', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '38', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '39', 'info:nombre', 'Producto 39'
put 'catalogo_de_productos', '39', 'info:descripcion', 'Descripción del producto 39'
put 'catalogo_de_productos', '39', 'info:precio', '390'
put 'catalogo_de_productos', '39', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '39', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '40', 'info:nombre', 'Producto 40'
put 'catalogo_de_productos', '40', 'info:descripcion', 'Descripción del producto 40'
put 'catalogo_de_productos', '40', 'info:precio', '400'
put 'catalogo_de_productos', '40', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '40', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '41', 'info:nombre', 'Producto 41'
put 'catalogo_de_productos', '41', 'info:descripcion', 'Descripción del producto 41'
put 'catalogo_de_productos', '41', 'info:precio', '410'
put 'catalogo_de_productos', '41', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '41', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '42', 'info:nombre', 'Producto 42'
put 'catalogo_de_productos', '42', 'info:descripcion', 'Descripción del producto 42'
put 'catalogo_de_productos', '42', 'info:precio', '420'
put 'catalogo_de_productos', '42', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '42', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '43', 'info:nombre', 'Producto 43'
put 'catalogo_de_productos', '43', 'info:descripcion', 'Descripción del producto 43'
put 'catalogo_de_productos', '43', 'info:precio', '430'
put 'catalogo_de_productos', '43', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '43', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '44', 'info:nombre', 'Producto 44'
put 'catalogo_de_productos', '44', 'info:descripcion', 'Descripción del producto 44'
put 'catalogo_de_productos', '44', 'info:precio', '440'
put 'catalogo_de_productos', '44', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '44', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '45', 'info:nombre', 'Producto 45'
put 'catalogo_de_productos', '45', 'info:descripcion', 'Descripción del producto 45'
put 'catalogo_de_productos', '45', 'info:precio', '450'
put 'catalogo_de_productos', '45', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '45', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '46', 'info:nombre', 'Producto 46'
put 'catalogo_de_productos', '46', 'info:descripcion', 'Descripción del producto 46'
put 'catalogo_de_productos', '46', 'info:precio', '460'
put 'catalogo_de_productos', '46', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '46', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '47', 'info:nombre', 'Producto 47'
put 'catalogo_de_productos', '47', 'info:descripcion', 'Descripción del producto 47'
put 'catalogo_de_productos', '47', 'info:precio', '470'
put 'catalogo_de_productos', '47', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '47', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '48', 'info:nombre', 'Producto 48'
put 'catalogo_de_productos', '48', 'info:descripcion', 'Descripción del producto 48'
put 'catalogo_de_productos', '48', 'info:precio', '480'
put 'catalogo_de_productos', '48', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '48', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '49', 'info:nombre', 'Producto 49'
put 'catalogo_de_productos', '49', 'info:descripcion', 'Descripción del producto 49'
put 'catalogo_de_productos', '49', 'info:precio', '490'
put 'catalogo_de_productos', '49', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '49', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '50', 'info:nombre', 'Producto 50'
put 'catalogo_de_productos', '50', 'info:descripcion', 'Descripción del producto 50'
put 'catalogo_de_productos', '50', 'info:precio', '500'
put 'catalogo_de_productos', '50', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '50', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '51', 'info:nombre', 'Producto 51'
put 'catalogo_de_productos', '51', 'info:descripcion', 'Descripción del producto 51'
put 'catalogo_de_productos', '51', 'info:precio', '510'
put 'catalogo_de_productos', '51', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '51', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '52', 'info:nombre', 'Producto 52'
put 'catalogo_de_productos', '52', 'info:descripcion', 'Descripción del producto 52'
put 'catalogo_de_productos', '52', 'info:precio', '520'
put 'catalogo_de_productos', '52', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '52', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '53', 'info:nombre', 'Producto 53'
put 'catalogo_de_productos', '53', 'info:descripcion', 'Descripción del producto 53'
put 'catalogo_de_productos', '53', 'info:precio', '530'
put 'catalogo_de_productos', '53', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '53', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '54', 'info:nombre', 'Producto 54'
put 'catalogo_de_productos', '54', 'info:descripcion', 'Descripción del producto 54'
put 'catalogo_de_productos', '54', 'info:precio', '540'
put 'catalogo_de_productos', '54', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '54', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '55', 'info:nombre', 'Producto 55'
put 'catalogo_de_productos', '55', 'info:descripcion', 'Descripción del producto 55'
put 'catalogo_de_productos', '55', 'info:precio', '550'
put 'catalogo_de_productos', '55', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '55', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '56', 'info:nombre', 'Producto 56'
put 'catalogo_de_productos', '56', 'info:descripcion', 'Descripción del producto 56'
put 'catalogo_de_productos', '56', 'info:precio', '560'
put 'catalogo_de_productos', '56', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '56', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '57', 'info:nombre', 'Producto 57'
put 'catalogo_de_productos', '57', 'info:descripcion', 'Descripción del producto 57'
put 'catalogo_de_productos', '57', 'info:precio', '570'
put 'catalogo_de_productos', '57', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '57', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '58', 'info:nombre', 'Producto 58'
put 'catalogo_de_productos', '58', 'info:descripcion', 'Descripción del producto 58'
put 'catalogo_de_productos', '58', 'info:precio', '580'
put 'catalogo_de_productos', '58', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '58', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '59', 'info:nombre', 'Producto 59'
put 'catalogo_de_productos', '59', 'info:descripcion', 'Descripción del producto 59'
put 'catalogo_de_productos', '59', 'info:precio', '590'
put 'catalogo_de_productos', '59', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '59', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '60', 'info:nombre', 'Producto 60'
put 'catalogo_de_productos', '60', 'info:descripcion', 'Descripción del producto 60'
put 'catalogo_de_productos', '60', 'info:precio', '600'
put 'catalogo_de_productos', '60', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '60', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '61', 'info:nombre', 'Producto 61'
put 'catalogo_de_productos', '61', 'info:descripcion', 'Descripción del producto 61'
put 'catalogo_de_productos', '61', 'info:precio', '610'
put 'catalogo_de_productos', '61', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '61', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '62', 'info:nombre', 'Producto 62'
put 'catalogo_de_productos', '62', 'info:descripcion', 'Descripción del producto 62'
put 'catalogo_de_productos', '62', 'info:precio', '620'
put 'catalogo_de_productos', '62', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '62', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '63', 'info:nombre', 'Producto 63'
put 'catalogo_de_productos', '63', 'info:descripcion', 'Descripción del producto 63'
put 'catalogo_de_productos', '63', 'info:precio', '630'
put 'catalogo_de_productos', '63', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '63', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '64', 'info:nombre', 'Producto 64'
put 'catalogo_de_productos', '64', 'info:descripcion', 'Descripción del producto 64'
put 'catalogo_de_productos', '64', 'info:precio', '640'
put 'catalogo_de_productos', '64', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '64', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '65', 'info:nombre', 'Producto 65'
put 'catalogo_de_productos', '65', 'info:descripcion', 'Descripción del producto 65'
put 'catalogo_de_productos', '65', 'info:precio', '650'
put 'catalogo_de_productos', '65', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '65', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '66', 'info:nombre', 'Producto 66'
put 'catalogo_de_productos', '66', 'info:descripcion', 'Descripción del producto 66'
put 'catalogo_de_productos', '66', 'info:precio', '660'
put 'catalogo_de_productos', '66', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '66', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '67', 'info:nombre', 'Producto 67'
put 'catalogo_de_productos', '67', 'info:descripcion', 'Descripción del producto 67'
put 'catalogo_de_productos', '67', 'info:precio', '670'
put 'catalogo_de_productos', '67', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '67', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '68', 'info:nombre', 'Producto 68'
put 'catalogo_de_productos', '68', 'info:descripcion', 'Descripción del producto 68'
put 'catalogo_de_productos', '68', 'info:precio', '680'
put 'catalogo_de_productos', '68', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '68', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '69', 'info:nombre', 'Producto 69'
put 'catalogo_de_productos', '69', 'info:descripcion', 'Descripción del producto 69'
put 'catalogo_de_productos', '69', 'info:precio', '690'
put 'catalogo_de_productos', '69', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '69', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '70', 'info:nombre', 'Producto 70'
put 'catalogo_de_productos', '70', 'info:descripcion', 'Descripción del producto 70'
put 'catalogo_de_productos', '70', 'info:precio', '700'
put 'catalogo_de_productos', '70', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '70', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '71', 'info:nombre', 'Producto 71'
put 'catalogo_de_productos', '71', 'info:descripcion', 'Descripción del producto 71'
put 'catalogo_de_productos', '71', 'info:precio', '710'
put 'catalogo_de_productos', '71', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '71', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '72', 'info:nombre', 'Producto 72'
put 'catalogo_de_productos', '72', 'info:descripcion', 'Descripción del producto 72'
put 'catalogo_de_productos', '72', 'info:precio', '720'
put 'catalogo_de_productos', '72', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '72', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '73', 'info:nombre', 'Producto 73'
put 'catalogo_de_productos', '73', 'info:descripcion', 'Descripción del producto 73'
put 'catalogo_de_productos', '73', 'info:precio', '730'
put 'catalogo_de_productos', '73', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '73', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '74', 'info:nombre', 'Producto 74'
put 'catalogo_de_productos', '74', 'info:descripcion', 'Descripción del producto 74'
put 'catalogo_de_productos', '74', 'info:precio', '740'
put 'catalogo_de_productos', '74', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '74', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '75', 'info:nombre', 'Producto 75'
put 'catalogo_de_productos', '75', 'info:descripcion', 'Descripción del producto 75'
put 'catalogo_de_productos', '75', 'info:precio', '750'
put 'catalogo_de_productos', '75', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '75', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '76', 'info:nombre', 'Producto 76'
put 'catalogo_de_productos', '76', 'info:descripcion', 'Descripción del producto 76'
put 'catalogo_de_productos', '76', 'info:precio', '760'
put 'catalogo_de_productos', '76', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '76', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '77', 'info:nombre', 'Producto 77'
put 'catalogo_de_productos', '77', 'info:descripcion', 'Descripción del producto 77'
put 'catalogo_de_productos', '77', 'info:precio', '770'
put 'catalogo_de_productos', '77', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '77', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '78', 'info:nombre', 'Producto 78'
put 'catalogo_de_productos', '78', 'info:descripcion', 'Descripción del producto 78'
put 'catalogo_de_productos', '78', 'info:precio', '780'
put 'catalogo_de_productos', '78', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '78', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '79', 'info:nombre', 'Producto 79'
put 'catalogo_de_productos', '79', 'info:descripcion', 'Descripción del producto 79'
put 'catalogo_de_productos', '79', 'info:precio', '790'
put 'catalogo_de_productos', '79', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '79', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '80', 'info:nombre', 'Producto 80'
put 'catalogo_de_productos', '80', 'info:descripcion', 'Descripción del producto 80'
put 'catalogo_de_productos', '80', 'info:precio', '800'
put 'catalogo_de_productos', '80', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '80', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '81', 'info:nombre', 'Producto 81'
put 'catalogo_de_productos', '81', 'info:descripcion', 'Descripción del producto 81'
put 'catalogo_de_productos', '81', 'info:precio', '810'
put 'catalogo_de_productos', '81', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '81', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '82', 'info:nombre', 'Producto 82'
put 'catalogo_de_productos', '82', 'info:descripcion', 'Descripción del producto 82'
put 'catalogo_de_productos', '82', 'info:precio', '820'
put 'catalogo_de_productos', '82', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '82', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '83', 'info:nombre', 'Producto 83'
put 'catalogo_de_productos', '83', 'info:descripcion', 'Descripción del producto 83'
put 'catalogo_de_productos', '83', 'info:precio', '830'
put 'catalogo_de_productos', '83', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '83', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '84', 'info:nombre', 'Producto 84'
put 'catalogo_de_productos', '84', 'info:descripcion', 'Descripción del producto 84'
put 'catalogo_de_productos', '84', 'info:precio', '840'
put 'catalogo_de_productos', '84', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '84', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '85', 'info:nombre', 'Producto 85'
put 'catalogo_de_productos', '85', 'info:descripcion', 'Descripción del producto 85'
put 'catalogo_de_productos', '85', 'info:precio', '850'
put 'catalogo_de_productos', '85', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '85', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '86', 'info:nombre', 'Producto 86'
put 'catalogo_de_productos', '86', 'info:descripcion', 'Descripción del producto 86'
put 'catalogo_de_productos', '86', 'info:precio', '860'
put 'catalogo_de_productos', '86', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '86', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '87', 'info:nombre', 'Producto 87'
put 'catalogo_de_productos', '87', 'info:descripcion', 'Descripción del producto 87'
put 'catalogo_de_productos', '87', 'info:precio', '870'
put 'catalogo_de_productos', '87', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '87', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '88', 'info:nombre', 'Producto 88'
put 'catalogo_de_productos', '88', 'info:descripcion', 'Descripción del producto 88'
put 'catalogo_de_productos', '88', 'info:precio', '880'
put 'catalogo_de_productos', '88', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '88', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '89', 'info:nombre', 'Producto 89'
put 'catalogo_de_productos', '89', 'info:descripcion', 'Descripción del producto 89'
put 'catalogo_de_productos', '89', 'info:precio', '890'
put 'catalogo_de_productos', '89', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '89', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '90', 'info:nombre', 'Producto 90'
put 'catalogo_de_productos', '90', 'info:descripcion', 'Descripción del producto 90'
put 'catalogo_de_productos', '90', 'info:precio', '900'
put 'catalogo_de_productos', '90', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '90', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '91', 'info:nombre', 'Producto 91'
put 'catalogo_de_productos', '91', 'info:descripcion', 'Descripción del producto 91'
put 'catalogo_de_productos', '91', 'info:precio', '910'
put 'catalogo_de_productos', '91', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '91', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '92', 'info:nombre', 'Producto 92'
put 'catalogo_de_productos', '92', 'info:descripcion', 'Descripción del producto 92'
put 'catalogo_de_productos', '92', 'info:precio', '920'
put 'catalogo_de_productos', '92', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '92', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '93', 'info:nombre', 'Producto 93'
put 'catalogo_de_productos', '93', 'info:descripcion', 'Descripción del producto 93'
put 'catalogo_de_productos', '93', 'info:precio', '930'
put 'catalogo_de_productos', '93', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '93', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '94', 'info:nombre', 'Producto 94'
put 'catalogo_de_productos', '94', 'info:descripcion', 'Descripción del producto 94'
put 'catalogo_de_productos', '94', 'info:precio', '940'
put 'catalogo_de_productos', '94', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '94', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '95', 'info:nombre', 'Producto 95'
put 'catalogo_de_productos', '95', 'info:descripcion', 'Descripción del producto 95'
put 'catalogo_de_productos', '95', 'info:precio', '950'
put 'catalogo_de_productos', '95', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '95', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '96', 'info:nombre', 'Producto 96'
put 'catalogo_de_productos', '96', 'info:descripcion', 'Descripción del producto 96'
put 'catalogo_de_productos', '96', 'info:precio', '960'
put 'catalogo_de_productos', '96', 'info:categoria', 'categoria2'
put 'catalogo_de_productos', '96', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '97', 'info:nombre', 'Producto 97'
put 'catalogo_de_productos', '97', 'info:descripcion', 'Descripción del producto 97'
put 'catalogo_de_productos', '97', 'info:precio', '970'
put 'catalogo_de_productos', '97', 'info:categoria', 'categoria3'
put 'catalogo_de_productos', '97', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '98', 'info:nombre', 'Producto 98'
put 'catalogo_de_productos', '98', 'info:descripcion', 'Descripción del producto 98'
put 'catalogo_de_productos', '98', 'info:precio', '980'
put 'catalogo_de_productos', '98', 'info:categoria', 'categoria4'
put 'catalogo_de_productos', '98', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '99', 'info:nombre', 'Producto 99'
put 'catalogo_de_productos', '99', 'info:descripcion', 'Descripción del producto 99'
put 'catalogo_de_productos', '99', 'info:precio', '990'
put 'catalogo_de_productos', '99', 'info:categoria', 'categoria5'
put 'catalogo_de_productos', '99', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
put 'catalogo_de_productos', '100', 'info:nombre', 'Producto 100'
put 'catalogo_de_productos', '100', 'info:descripcion', 'Descripción del producto 100'
put 'catalogo_de_productos', '100', 'info:precio', '1000'
put 'catalogo_de_productos', '100', 'info:categoria', 'categoria1'
put 'catalogo_de_productos', '100', 'info:fecha_creacion', '2025-05-11T00:00:00Z'
EOF

echo "Se ha creado la tabla 'catalogo_de_productos' y se han insertado los datos correctamente."
